Repository gravity-ui/markdown-editor, pull requests merged in 2024-10, with the labels that each got.

#429 feat: update prosemirror deps
  package-lock.json
  package.json
Labels: dependencies

#430 feat: update codemirror deps
  package-lock.json
  package.json
Labels: dependencies

#417 feat(deps)!: updated transform version 4.32.2
  package-lock.json
  package.json
  src/extensions/yfm/YfmNote/plugins/YfmNoteTooltipPlugin/index.scss
  src/extensions/yfm/YfmNote/plugins/YfmNoteTooltipPlugin/index.tsx
  src/extensions/yfm/YfmTabs/YfmTabs.test.ts
  src/extensions/yfm/YfmTabs/YfmTabsSpecs/md-plugin.ts
  tests/dispatch-event.ts
  tests/setup.ts
Labels: dependencies, breaking change

#446 docs: added how-to-add-editor-with-nextjs.md
  docs/how-to-add-editor-with-nextjs.md
Labels: documentation
